likecoin/likecoin-button

functions/ssrapp.js

+ Increase cache time to 10min

+ Add SENTRY_REPORT_URI as function config

---

src/locales/client/ja.json

probably `<i18n>` tag does not like locale string begining with `{`

! Fix/mitigate ja render error

---

src/pages/in/embed/_id/button.vue

Depends on likecoin/likecoin-store#798

* Use new register/login flow

---

src/components/LikeButton.vue
src/pages/in/embed/_id/button.vue

Depends on likecoin/likecoin-store#798

Update LikeButton for upcoming change

---

src/pages/in/embed/_id/button.vue
src/pages/in/like/_id/index.vue
src/util/api/api.js

+ Add pixel log for clickLike and popupLikeButton

+ Add is3rdPartyCookieSupport in like button api query

---

src/pages/in/embed/_id/button.vue
src/pages/in/embed/_id/list.vue
src/pages/in/embed/_id/mini.vue
src/pages/in/like/_id/index.vue

hopefully it will make the colorful background appears slightly faster for logged-in user

= Move async data fetching to `created()` hook

---

functions/package-lock.json
functions/package.json
functions/ssrapp.js

This suppose to improve startup time

= Use `nuxt-start` for function

---

src/components/embed/mixin.js
src/pages/in/embed/_id/list.vue
src/pages/in/like/_id/index.vue
src/plugins/axios.js
src/util/api/api.js
src/util/url.js

Also bound timeout to 5s to see if firebase fn timeout is related to title fetch

Reduce likebutton load time due to title fetch

---

src/pages/in/embed/_id/list.vue
src/plugins/axios.js
src/util/api/api.js

Reduce risk of SSRF and support SPA title
However might introduce title fetch delay since db title fetch is by batch

 + Fetch title from db instead of direct axios

---

src/components/LikeButton.vue
src/pages/in/embed/_id/button.vue

Minor UI changes

---

src/pages/in/embed/_id/button.vue
src/util/client.js

https://webkit.org/blog/8311/intelligent-tracking-prevention-2-0/
https://webkit.org/blog/8124/introducing-storage-access-api/

🚑 Detect if cookie are blocked by storage access api

---

src/components/embed/EmbedUserInfo.vue
src/locales/client/cn.json
src/locales/client/en.json
src/locales/client/ja.json
src/locales/client/zh.json
src/pages/in/like/_id/index.vue

Use inline style to render faster without waiting bundles

💄 Better handle UI before loading CSS for single like page

---

src/pages/in/embed/_id/button.vue
src/pages/in/like/_id/index.vue

Depends on likecoin/likecoin-store#1030

⚡️ Add is_popup=1 qs in registration URL

---

functions/package-lock.json
functions/package.json
src/nuxt.config.js
src/package-lock.json
src/package.json

Our sentry is currently spamed by `cannot mutate read-only object` error, a fix in https://nuxtjs.org/guide/release-notes/#v2.5.0 should solve this problem

⬆️ Upgrade nuxt@2.6.3

---

src/middleware/cookie.js

currently this middleware is setting cookies with different paths

🐛 Fix duplicate setting of cookie

---

src/components/LikeButton.vue
src/experiments/likeButtonV2/index.js
src/pages/in/embed/_id/button.vue

Preparation of LikeButton AB Test round 2

---

src/experiments/likeButtonV2/index.js
src/pages/in/embed/_id/button.vue
src/pages/in/like/_id/index.vue

⚗ Update experiment params
Will update exp id after I get proper events listed into GA

🔊 Clean up event logs

---

firebase.json
functions/package-lock.json
functions/package.json
src/nuxt.config.js
src/package.json
src/server_middleware/header-listener.js

inject `unsafe-inline` in header using serverMiddleware

💩 Mitigate nuxt CSP issue

---

src/experiments/like-button/index.js
src/layouts/embed.vue
src/nuxt.config.js
src/pages/in/embed/_id/button.vue

⚗️ Prepare experiment for showing display name

---

src/experiments/like-button/index.js
src/locales/client/zh.json
src/nuxt.config.js
src/pages/in/embed/_id/button.vue

Reverts likecoin/likecoin-button#226

⚗ End likebutton text test

---

functions/ssrapp.js

currently nuxt renderer might throw 4xx error, but the cache header is already placed, making the 4xx error staying in cache. this pr add condition cache header on end of request header listener
Also make vary:cookie sensitive to abtesting config in nuxt.config, which can improve cachability if not running ab test

⚡️ Fix cache behaviour on http error and cookie

---

src/mixins/embed.js

Currently, get bookmark status may return 404 if no bookmark record

Fix unable to catch fetching bookmark 404

---

src/mixins/embed.js
src/pages/in/embed/_id/button.vue
src/pages/in/like/_id/index.vue

🚸 Allow whitelisted likers to follow creator

---

src/mixins/embed-button.js

My guess is this error is caused by putting browser tab into background/inactive state

🔇 Reduce error log of timeout and network error from read timer

---

src/mixins/embed.js
src/pages/in/embed/_id/button.vue
src/pages/in/like/_id/index.vue

Deploy after follow data migration is complete

⏪ Revert "Temporally disable follow button #277"

---

src/components/LikeButtonV2/LikeButtonV2.badge.vue
src/components/LikeButtonV2/LikeButtonV2.clapBits.vue
src/components/LikeButtonV2/LikeButtonV2.stateTable.vue
src/components/LikeButtonV2/LikeButtonV2.stories.js
src/components/LikeButtonV2/LikeButtonV2.vue

Add LikeButton state table & fix badge

---

src/mixins/embed-button.js
src/pages/in/embed/_id/button.vue

Should be useful for staging env

✨ Activate preview mode via qs `preview=1`

---

src/components/LikeCoinButtonWidget/LikeCoinButtonWidget.vue
src/locales/client/cn.json
src/locales/client/en.json
src/locales/client/zh.json
src/mixins/embed.js
src/pages/in/embed/_id/button.vue
src/pages/in/like/_id/index.vue
src/util/api/api.js

Depends on https://github.com/likecoin/liker-land/pull/349

Civic Liker 2.0 feature

---

src/pages/in/like/_id/index.vue

Not sure if this will fix the self-liking issue, but making it consistent would be better somehow

🎨 Make the action behaviour on popup consistent with postMessage

---

src/mixins/embed.js

fix redundant api calls on non-2.0 users

:zap: restrict api call to /civic/suupport/users to only civicLiker2.0

---

src/mixins/embed.js
src/pages/in/like/_id/index.vue

No clue about the slow performance on redirecting to liker.land
For now, just adding a loading indicator to let users know something is happening
Before
https://user-images.githubusercontent.com/17264716/114147739-96691c80-994b-11eb-866b-57f6ccedc702.mov
After
https://user-images.githubusercontent.com/17264716/114147685-894c2d80-994b-11eb-8bc1-bfbca9341010.mov

🚸 Indicate loading state when going to portfolio

---

src/locales/client/en.json

50%Banana team suggest change in English locale

---

src/mixins/embed-button.js
src/pages/in/like/_id/index.vue

Do not redirect to register if the `like` page is not called as popup

✨ Do not redirect to login if not popup in like page

---

functions/package-lock.json
functions/package.json
src/mixins/embed.js
src/package-lock.json
src/package.json
src/util/api/api.js
src/util/cosmos.js

✨ Add iscn_id check owner liker data

✨ Add iscn_id check owner liker data

---

src/mixins/nft.js

Requires https://github.com/likecoin/liker-land/pull/588

👽 [NFT Widget] Collect at liker.land

---

src/mixins/embed.js

https://user-images.githubusercontent.com/17264716/188251234-de2121b0-cde7-44ab-8c65-95d7a57bade8.mov

🐛 [NFT Widget] Fix unable to like

---

src/components/NFTWidget/CollectActionBar.vue

Fix https://github.com/likecoin/likecoin-wordpress/issues/202

🐛 [NFT Widget] Fix swapped collector & collected count

---

src/mixins/embed.js

Know issue: since display name shows majority stakeholder instead of iscn owner, the displayed name and actual wallet in url might not align

🐛 Fix on click avatar for iscn button

---

src/mixins/embed.js

✨ Use owner to show

---

src/assets/css/v2/global.css
src/components/LikeCoinButtonWidgetV2/LikeCoinButtonWidgetV2.vue
src/pages/in/like/_id/index.vue

💄 Use full width for popup like action & adjust for English

---

functions/package-lock.json
functions/package.json
src/components/IdentityV2/IdentityV2.avatar.vue
src/nuxt.config.js
src/package-lock.json
src/package.json
src/util/nft.js
src/util/ui.js

⚡️ Use resized image and lazy load iscn-js

---

src/components/LikeCoinButtonWidgetV2/LikeCoinButtonWidgetV2.vue
src/locales/client/cn.json
src/locales/client/en.json
src/locales/client/zh.json
src/pages/in/embed/_id/button.vue
src/pages/in/like/_id/index.vue
src/util/api/api.js

✨ Add upgrade link for widget v2

---

src/plugins/vue-i18n.js

Add support for qs language override
Refactor judgement to prioritze according nav.language order

🌐 Refactor i18n detection and support language qs

---

firebase.json
functions/.env.likecoin-button
functions/.env.likecoin-button-develop
functions/imagessr.js
functions/index.js
functions/package-lock.json
functions/package.json

Add `/image` to trigger image rendering via puppeteer
it seems blurry image would be seen on device with different dpi, so a `scale` qs is added in case we need it

✨ Add image rendering function for embed button

---

src/components/NFTWidget/index.vue
src/pages/in/embed/nft/index.vue

✨ Add query to hide cover and like bar in widget

---

src/mixins/nft.js
src/pages/in/embed/nft/button.vue
src/pages/in/embed/nft/index.vue

✨ Add button only page and change label via query

---

src/constant/index.js
src/mixins/nft.js
src/util/api/api.js

Replace public owner API with indexer owner API.
Depends on https://github.com/likecoin/likecoin-chain-tx-indexer/pull/111

👔 Make count data source align with liker.land

---

src/util/url.js

we want to support SPA pages but remove other hash that does not affect page content

✨ Remove URL hash if not SPA route

---

public_base/robots.txt
src/nuxt.config.js

https://developers.google.com/search/blog/2022/01/robots-meta-tag-indexifembedded

🔍️ Use meta for robots and add indexifembedded
